@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/MooseX-DeclareX-Privacy/project>
	deps:runtime-requirement         [ deps:on "MooseX::DeclareX 0.008"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "MooseX::Privacy 0.05"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::Fatal"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.96"^^deps:CpanId ].

